/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.webcrawler;

import com.test.webcrawler.manager.ProcessManager;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 *
 * @author jose
 */
public class WebCrawlerMain extends javax.swing.JFrame {

    private ApplicationContext context;

    private ProcessManager processManager;

    public static final String DOWNLOAD_TEXT = "Downloading file ";

    public ApplicationContext getContext() {
        return context;
    }

    public void setContext(ApplicationContext context) {
        this.context = context;
    }

    public ProcessManager getProcessManager() {
        return processManager;
    }

    public void setProcessManager(ProcessManager processManager) {
        this.processManager = processManager;
    }

    public JButton getBtnDownload() {
        return btnDownload;
    }

    public void setBtnDownload(JButton btnDownload) {
        this.btnDownload = btnDownload;
    }

    public JLabel getjLabel1() {
        return lblEnterURL;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.lblEnterURL = jLabel1;
    }

    public JTextField getTxtURL() {
        return txtURL;
    }

    public void setTxtURL(JTextField txtURL) {
        this.txtURL = txtURL;
    }

    public JLabel getLblDownload() {
        return lblDownload;
    }

    public void setLblDownload(JLabel lblDownload) {
        this.lblDownload = lblDownload;
    }

    public JLabel getLblEnterURL() {
        return lblEnterURL;
    }

    public void setLblEnterURL(JLabel lblEnterURL) {
        this.lblEnterURL = lblEnterURL;
    }

    public JPanel getPnlDownload() {
        return pnlDownload;
    }

    public void setPnlDownload(JPanel pnlDownload) {
        this.pnlDownload = pnlDownload;
    }

    public JProgressBar getProgBarDownload() {
        return progBarDownload;
    }

    public void setProgBarDownload(JProgressBar progBarDownload) {
        this.progBarDownload = progBarDownload;
    }
    
    

    /**
     * Creates new form WebCrawlerMain
     */
    public WebCrawlerMain() {
        initComponents();
        initSpringComponents();
        fixComponentVisibility();
    }
    
    public void setFileInfo(String fileName, int length) {
    
        pnlDownload.setVisible(true);
        lblDownload.setText(DOWNLOAD_TEXT + fileName);
    
    }
    
    private void fixComponentVisibility() {
        pnlDownload.setVisible(false);
    }

    private void initSpringComponents() {
        context = new ClassPathXmlApplicationContext("applicationContext.xml");
        processManager = (ProcessManager) context.getBean("processManager");
        processManager.setParentComponent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterURL = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        btnDownload = new javax.swing.JButton();
        pnlDownload = new javax.swing.JPanel();
        progBarDownload = new javax.swing.JProgressBar();
        lblDownload = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Downloader");

        lblEnterURL.setText("Enter URL");

        txtURL.setToolTipText("Type URL here");
        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });

        btnDownload.setText("Download Images!");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        lblDownload.setText("jLabel2");

        javax.swing.GroupLayout pnlDownloadLayout = new javax.swing.GroupLayout(pnlDownload);
        pnlDownload.setLayout(pnlDownloadLayout);
        pnlDownloadLayout.setHorizontalGroup(
            pnlDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDownloadLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDownloadLayout.createSequentialGroup()
                        .addComponent(lblDownload)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progBarDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDownloadLayout.setVerticalGroup(
            pnlDownloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDownloadLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDownload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progBarDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnterURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDownload))
                    .addComponent(pnlDownload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterURL)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDownload))
                .addGap(84, 84, 84)
                .addComponent(pnlDownload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed

        disableSearching();
        processManager.processDownload(txtURL.getText(), null);

    }//GEN-LAST:event_btnDownloadActionPerformed

    public void disableSearching() {
        btnDownload.setEnabled(false);
        txtURL.setEditable(false);
        txtURL.setEnabled(false);
    }
    
    public void enableSearching() {
        btnDownload.setEnabled(true);
        txtURL.setEditable(true);
        txtURL.setEnabled(true);
        progBarDownload.setValue(0);
        pnlDownload.setVisible(false);
    }
    
    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebCrawlerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebCrawlerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebCrawlerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebCrawlerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebCrawlerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDownload;
    private javax.swing.JLabel lblDownload;
    private javax.swing.JLabel lblEnterURL;
    private javax.swing.JPanel pnlDownload;
    private javax.swing.JProgressBar progBarDownload;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
